# Generated by Django 2.0.5 on 2018-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('stime', models.DateTimeField()),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
